// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Label struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Label     string
}

type Project struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Completed bool
	TimeSpent int32
}

type Task struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Task          string
	Completed     bool
	ProjectID     uuid.NullUUID
	Description   sql.NullString
	TimeLimitType sql.NullString
	TimeLimit     sql.NullInt32
}
