// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Label struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Label     string
}

type Project struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	TimeSpent     int32
	TimeLimitType string
	TimeLimit     int32
	Completed     bool
}

type Task struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Task        string
	Description sql.NullString
	Completed   bool
	ProjectID   uuid.NullUUID
}
